const labels = {
  Learn_CSS: 'Вивчення CSS',
  Reference: 'Довідник',
  Guides: 'Посібники',
  Combinators: 'Комбінатори',
  Functions: 'Функції',
  Colors: 'Кольори',
  Applying_color_to_HTML_elements_using_CSS:
    'Застосування кольору до елементів HTML за допомогою CSS',
  Conditional_rules: 'Умовні директиви',
  Using_feature_queries: 'Застосування запитів можливостей',
  Nesting: 'Вкладеність',
  Using_CSS_nesting: 'Застосування вкладеності в CSS',
  Nesting_and_specificity: 'Вкладеність і специфічність',
  'Nesting_at-rules': 'Директиви вкладеності',
  CSS_first_steps: 'Перші кроки у CSS',
  CSS_first_steps_overview: 'Перші кроки у CSS — огляд',
  What_is_CSS: 'Що таке CSS?',
  Getting_started_with_CSS: 'Початок роботи з CSS',
  How_CSS_is_structured: 'Яку структуру має CSS',
  How_CSS_works: 'Як працює CSS',
  Using_your_new_knowledge: 'Застосування щойно набутих знань',
  CSS_building_blocks: 'Конструктивні блоки CSS',
  CSS_building_blocks_overview: 'Конструктивні блоки CSS — огляд',
  Cascade_and_inheritance: 'Каскад і успадкування',
  CSS_selectors: 'Селектори CSS',
  The_box_model: 'Рамкова модель',
  Backgrounds_and_borders: 'Межі та фони',
  Handling_different_text_directions: 'Обробка різних напрямів письма',
  Overflowing_content: 'Переповнення вмісту',
  Values_and_units: 'Значення та одиниці вимірювання',
  Sizing_items_in_CSS: 'Задання розмірів елементів у CSS',
  Images_media_and_form_elements: 'Зображення, медіаконтент і елементи форм',
  Styling_tables: 'Оформлення таблиць',
  Debugging_CSS: 'Зневадження CSS',
  Organizing_your_CSS: 'Організація коду на CSS',
  Styling_text: 'Оформлення тексту',
  Styling_text_overview: 'Оформлення тексту — огляд',
  Fundamental_text_and_font_styling: 'Базове оформлення тексту та шрифта',
  Styling_lists: 'Оформлення списків',
  Styling_links: 'Оформлення посилань',
  Web_fonts: 'Вебшрифти',
  Assessment_typesetting_a_community_school_homepage:
    'Оцінювання: верстання шкільного вебсайту',
  CSS_layout: 'Компонування CSS',
  CSS_layout_overview: 'Компонування CSS — огляд',
  Layout_introduction: 'Знайомство з компонуванням',
  Normal_Flow: 'Звичайний плин',
  Flexbox: 'Флексбокс',
  Grids: 'Сітки',
  Floats: 'Пливуни',
  Positioning: 'Позиціювання',
  'Multiple-column_Layout': 'Багатоколонкове компонування',
  Responsive_design: 'Чуйний дизайн',
  Media_queries: 'Медіазапити — настанови для початківців',
  Legacy_Layout_Methods: 'Історичні способи верстання',
  Supporting_Older_Browsers: 'Підтримка старих браузерів',
  Fundamental_Layout_Comprehension: 'Фундаментальне розуміння компонування',
  Color_picker_tool: 'Інструмент для вибору кольору',
  'Box-shadow_generator': 'Генератор блокової тіні',
  'Border-image_generator': 'Генератор зображення для рамки',

  // TODO better place for that?
  Animations: 'Анімації',
  'Using CSS animations': 'Застосування анімацій CSS',
  'Backgrounds and Borders': 'Фони та рамки',
  'Using multiple backgrounds': 'Застосування кількох фонів',
  'Resizing background images': 'Зміна розмірів фонових зображень',
  'Box model': 'Рамкова модель',
  'Box alignment': 'Шикування рамки',
  Columns: 'Колонки',
  'Conditional rules': 'Умовні директиви',
  'CSSOM view': 'Представлення CSSOM',
  'Flow layout': 'Потокове компонування',
  Fonts: 'Шрифти',
  Grid: 'Сітки',
  Images: 'Зображення',
  'Lists and counters': 'Списки та лічильники',
  'Logical properties': 'Логічні властивості',
  'Media queries': 'Медіазапити',
  'Scroll snap': 'Захоплення прокручення',
  Shapes: 'Фігури',
  Text: 'Текст',
  Transforms: 'Перетворення',
  Transitions: 'Переходи',
  'Layout cookbook': 'Книга рецептів з компонування',
  Tools: 'Інструменти',
  'Box alignment in block layout': 'Шикування блоку при блоковому компонуванні',
  'Box alignment in flexbox': 'Шикування блоку при флексбоксі',
  'Box alignment in grid layout': 'Шикування блоку при сітковому компонуванні',
  'Box alignment in multi-column layout':
    'Шикування блоку при багатоколонковому компонуванні',
  'Introduction to the CSS basic box model':
    'Вступ до базової рамкової моделі CSS',
  'Mastering margin collapsing': 'Опанування перекриття зовнішніх полів',
  'Basic concepts of Multicol': 'Базові концепції багатоколонки',
  'Styling columns': 'Оформлення колонок',
  'Spanning and balancing': 'Заповнення та балансування',
  'Handling overflow in Multicol': 'Обробка переповнення у багатоколонці',
  'Content breaks in Multicol': 'Розриви вмісту в багатоколонці',
  'Using feature queries': 'Застосування запитів можливостей',
  'Coordinate systems': 'Координатні системи',
  'Basic concepts of Flexbox': 'Основні концепції Флексбоксу',
  'Comparison with other layout methods':
    'Порівняння з іншими способами компонування',
  'Aligning items in a flex container':
    'Шикування елементів у гнучкому контейнері',
  'Ordering flex items': 'Упорядкування гнучких елементів',
  'Controlling flex item ratios': 'Контроль пропорцій гнучких елементів',
  'Mastering wrapping of flex items':
    'Опанування перенесення гнучких елементів',
  'Typical use cases of Flexbox': 'Типові випадки для застосування Флексбоксу',
  'Backwards compatibility of Flexbox': 'Зворотна сумісність Флексбоксу',
  'Block and Inline layout in normal flow':
    'Блокове та рядкове компонування при звичайному плині',
  'In flow and Out of flow': 'У плині та поза плином',
  'Formatting contexts explained': 'Пояснення контекстів форматування',
  'Flow layout and writing modes': 'Потокове компонування та напрямки письма',
  'Flow layout and overflow': 'Потокове компонування та переповнення',
  'OpenType font features guide': 'Посібник з можливостей шрифтів OpenType',
  'Variable fonts guide': 'Посібник зі змінних шрифтів',
  'Basics concepts of grid layout': 'Основні ідеї розкладки за сіткою',
  'Relationship to other layout methods':
    "Зв'язок з іншими способами компонування",
  'Line-based placement': 'Розміщення на основі рядів',
  'Grid template areas': 'Області шаблону сітки',
  'Layout using named grid lines':
    'Компонування за допомогою іменованих рядів сітки',
  'Auto-placement in grid layout': 'Авторозміщення при сітковому компонуванні',
  'Grids, logical values and writing modes':
    'Сітки, логічні значення та напрям письма',
  'Grid layout and accessibility': 'Сіткове компонування та доступність',
  'Grid Layout and progressive enhancement':
    'Сіткове компонування та прогресивне покращення',
  'Realizing common layouts using grids':
    'Реалізація поширених макетів за допомогою сіток',
  Subgrid: 'Підсітка',
  'Masonry layout': 'Кладкове компонування',
  'Using CSS gradients': 'Застосування градієнтів CSS',
  'Using CSS counters': 'Застосування лічильників CSS',
  'Consistent list indentation': 'Узгоджені відступи у списках',
  'Basic concepts': 'Базові концепції',
  'Floating and positioning': 'Пливуни та позиціювання',
  'Margins, borders and padding':
    'Зовнішні відступи, межі та внутрішні відступи',
  Sizing: 'Задання розмірів',
  'Using media queries': 'Використання медіазапитів',
  'Using media queries for accessibility':
    'Використання медіазапитів для потреб доступності',
  'Testing media queries programmatically': 'Програмне тестування медіазапитів',
  'Understanding CSS z-index': 'Розуміння z-індексу у CSS',
  'Basic concepts of scroll snap': 'Основні принципи захоплення прокрутки',
  'Overview of shapes': 'Фігури — огляд',
  'Shapes from box values': 'Створення фігур на базі параметрів рамки',
  'Basic shapes': 'Основні фігури',
  'Shapes from images': 'Створення фігур із зображень',
  'Wrapping and breaking text': 'Переноси та розриви тексту',
  'Using transforms': 'Застосування перетворень',
  'Using transitions': 'Застосування переходів',
  'Media objects': "Медійні об'єкти",
  'Center an element': 'Центрування елемента',
  'Sticky footers': 'Липкий нижній колонтитул',
  'Split navigation': 'Розділена навігація',
  'Breadcrumb navigation': 'Навігація за хлібними крихтами',
  'List group with badges': 'Список елементів з розрізненням',
  Pagination: 'Розбиття на сторінки',
  Card: 'Картка',
  'Grid wrapper': 'Обгортка сітки',
  Modules: 'Модулі',
  Properties: 'Властивості',
  Selectors: 'Селектори',
  'Pseudo-classes': 'Псевдокласи',
  'Pseudo-elements': 'Псевдоелементи',
  'At-rules': 'Директиви',
  Types: 'Типи',
};

export default labels;
