const labels = {
  JavaScript: 'JavaScript',
  Overview: 'Огляд JavaScript',
  Tutorials: 'Підручники',
  Guide: 'Посібники з JavaScript',
  Guide_Introduction: 'Вступ',
  Guide_Grammar: 'Граматика та типи',
  Guide_Control_flow: 'Керування потоком та обробка помилок',
  Guide_Loops: 'Цикли та ітерування',
  Guide_Functions: 'Функції',
  Guide_Expressions: 'Вирази та оператори',
  Guide_Numbers: 'Числа та дати',
  Guide_Text: 'Форматування тексту',
  Guide_RegExp: 'Регулярні вирази',
  Guide_Indexed_collections: 'Колекції з індексами',
  Guide_keyed_collections: 'Колекції з ключами',
  Guide_Objects: "Робота з об'єктами",
  Guide_OOP: "Докладно про об'єктну модель",
  Guide_promises: 'Використання промісів',
  Guide_Iterators_Generators: 'Ітератори та генератори',
  Guide_Meta: 'Метапрограмування',
  Guide_Modules: 'Модулі JavaScript',
  Complete_beginners: 'Для цілковитих початківців',
  Basics: 'Основи JavaScript',
  First_steps: 'Перші кроки з JavaScript',
  Building_blocks: 'Конструктивні блоки JavaScript',
  Intermediate: 'Середній рівень',
  Introducing_objects: "Вступ до об'єктів у JavaScript",
  'Client-side_APIs': 'Клієнтські API Вебу',
  Frameworks: 'Клієнтські фреймворки у JavaScript',
  'Re-introduction': 'Повторний вступ до JavaScript',
  Data_structures: 'Структури даних у JavaScript',
  Equality: 'Порівняння на схожість і однаковість',
  Closures: 'Замикання',
  Advanced: 'Поглиблене вивчення',
  Inheritance: 'Наслідування та ланцюжок прототипів',
  Strict_mode: 'Суворий режим',
  Typed_arrays: 'Типізовані масиви JavaScript',
  Memory_Management: "Керування пам'яттю",
  Event_Loop: 'Модель багатопотоковості та Цикл подій',
  Reference: 'Довідник',
  Global_Objects: "Вбудовані об'єкти",
  Operators: 'Вирази та оператори',
  Statements: 'Інструкції та оголошення',
  Functions: 'Функції',
  Classes: 'Класи',
  Errors: 'Помилки',
  More: 'Різне',
  Lexical_grammar: 'Лексична граматика',
  Enumerability: 'Перелічуваність і належність властивостей',
  Data_types: 'Типи і структури даних',
  Iteration_protocols: 'Протоколи ітерування',
  Transitioning_to_strict_mode: 'Перехід до суворого режиму',
  Template_strings: 'Шаблонні літерали',
  Deprecated_features: 'Нерекомендовані можливості',
};

export default labels;
